apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bbooker-cert
  namespace: bbooker
spec:
  secretName: bbooker-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bbooker.dnabil.ovh
